### ISSUE TITLE
Can't try mioco's echo server example

### ISSUE THREAD

**Issue by vi** [dpc/mioco#81]
```
$ rustc --version
rustc 1.8.0-nightly (18b851bc5 2016-01-22)
$ grep mioco Cargo.lock 
name = "rust_mioco_test"
 "mioco 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)",
name = "mioco"
$ target/debug/rust_mioco_test 
Segmentation fault
$ rust-gdb -args target/debug/rust_mioco_test
...
(gdb) r
Starting program: /mnt/src/_/rust_mioco_test/target/debug/rust_mioco_test 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
[New Thread 0xf6fffb40 (LWP 23443)]
[New Thread 0xf6dffb40 (LWP 23444)]
[New Thread 0xf65ffb40 (LWP 23445)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xf6fffb40 (LWP 23443)]
0x565e1d6a in sys_common::net::TcpListener::socket_addr::hf48f84ba8af5633bGAs ()
(gdb) bt full
#0  0x565e1d6a in sys_common::net::TcpListener::socket_addr::hf48f84ba8af5633bGAs ()
No symbol table info available.
#1  0x565e1d3e in net::tcp::TcpListener::local_addr::h3dad58d2c54df282slj ()
No symbol table info available.
#2  0x565cdff1 in mio::sys::unix::tcp::TcpListener::local_addr (self=0xf6826018)
    at /home/vi/.cargo/registry/src/github.com-48ad6e4054423464/mio-0.5.0/src/sys/unix/tcp.rs:156
No locals.
#3  0x565cdfa1 in mio::net::tcp::TcpListener::local_addr (self=0xf6826018) at /home/vi/.cargo/registry/src/github.com-48ad6e4054423464/mio-0.5.0/src/net/tcp.rs:214
No locals.
#4  0x565bb4a6 in mioco::tcp::TcpListener::local_addr (self=0xf59ff864) at /home/vi/.cargo/registry/src/github.com-48ad6e4054423464/mioco-0.2.0/src/tcp.rs:25
No locals.
#5  0x5657e5ba in fnfn () at src/main.rs:20
        addr = V4 = {SocketAddrV4 = {inner = sockaddr_in = {sin_family = 2, sin_port = 45845, sin_addr = in_addr = {s_addr = 16777343}, 
              sin_zero = "\000\000\000\000\000\000\000"}}}
        listener = TcpListener = {RcEvented<mio::net::tcp::TcpListener> = {Rc<core::cell::RefCell<mioco::EventedShared<mio::net::tcp::TcpListener>>> = {
              _ptr = Shared<alloc::rc::RcBox<core::cell::RefCell<mioco::EventedShared<mio::net::tcp::TcpListener>>>> = {
                pointer = NonZero<*const alloc::rc::RcBox<core::cell::RefCell<mioco::EventedShared<mio::net::tcp::TcpListener>>>> = {0xf6826000}, 
                _marker = PhantomData<alloc::rc::RcBox<core::cell::RefCell<mioco::EventedShared<mio::net::tcp::TcpListener>>>>}}}}
#6  0x5657e470 in rust_mioco_test::boxed::F.FnBox<A>::call_box (self=0x1, args=0) at ../src/liballoc/boxed.rs:541
No locals.
#7  0x565ada17 in fnfn () at /home/vi/.cargo/registry/src/github.com-48ad6e4054423464/mioco-0.2.0/src/lib.rs:1007
        coroutine = 0xf778d00c
        f = Box<FnBox<()>>
        arg = 4151889932
#8  0x565ad2b8 in fnfn () at ../src/libstd/panic.rs:260
        f = closure = {4151889932}
        result = 0xf59ffbac
#9  0x565ad26f in mioco::sys_common::unwind::try::try_fn<closure> (opt_closure=0xf59ffafc "") at ../src/libstd/sys/common/unwind/mod.rs:153
        opt_closure = 0xf59ffafc
#10 0x565e6145 in __rust_try ()
No symbol table info available.
#11 0x565e35d8 in sys_common::unwind::try::inner_try::h58edf5aa3f4d3bba5bt ()
No symbol table info available.
#12 0x565ad1f6 in mioco::sys_common::unwind::try<closure> (f=closure = {...}) at ../src/libstd/sys/common/unwind/mod.rs:123
Python Exception <class 'gdb.error'> Cannot convert value to int.: 
        f = {RUST$ENCODED$ENUM$0$1$None = Some = {closure = {closure = {0}, 0x0}}}
#13 0x565acf6c in mioco::panic::recover<closure,core::result::Result<(), std::io::error::Error>> (f=closure = {...}) at ../src/libstd/panic.rs:260
        result = 0xf59ffbac
        result = None
#14 0x565abe3f in mioco::Coroutine::spawn::init_fn (arg=4151889932) at /home/vi/.cargo/registry/src/github.com-48ad6e4054423464/mioco-0.2.0/src/lib.rs:998
        res = Ok = {Ok = {0}}
        coroutine = 0x0
        id = CoroutineId = {0}
        ctx = 0x0
#15 0x565abd83 in Coroutine::spawn::init_fn::h782ba2051dd1f929wjc ()
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#16 0x00000000 in ?? ()
No symbol table info available.
```

System is i686 Debian Wheezy running x86_64 kernel.

**Comment by dpc** [comment]
So was it something regarding context-rs not working on i686? Please reopen if not. Mioco just recently migrated to context-rs 1.0 branch that is said to work well on other archs.
